### ISSUE TITLE
Docker only installing for version 12

### ISSUE THREAD

**Issue by furstenheim** [pgxn/docker-pgxn-tools#4]
Hi,
I maintain https://github.com/furstenheim/is_jsonb_valid, and I would like to run the tests with the tools.

For some reason (I guess docker cache ?¿) I can only execute the tests with version 12.

This succeeds
```
docker run -it --rm --mount "type=bind,src=$(pwd),dst=/repo" pgxn/pgxn-tools sh -c 'cd /repo && pg-start 12 && pg-build-test'
```

This fails
```
docker run -it --rm --mount "type=bind,src=$(pwd),dst=/repo" pgxn/pgxn-tools sh -c 'cd /repo && pg-start 10 && pg-build-test'
```

Any version different from 12 fails with `No function matches the given name and argument types. You might need to add explicit type casts.`.

The logs at `sudo make install` look slightly different

v12:

```
+ sudo make install
/bin/mkdir -p '/usr/share/postgresql/12/extension'
/bin/mkdir -p '/usr/share/postgresql/12/extension'
/bin/mkdir -p '/usr/lib/postgresql/12/lib'
/usr/bin/install -c -m 644 .//is_jsonb_valid.control '/usr/share/postgresql/12/extension/'
/usr/bin/install -c -m 644 .//is_jsonb_valid--0.1.2.sql  '/usr/share/postgresql/12/extension/'
/usr/bin/install -c -m 755  is_jsonb_valid.so '/usr/lib/postgresql/12/lib/'
/bin/mkdir -p '/usr/lib/postgresql/12/lib/bitcode/is_jsonb_valid'
/bin/mkdir -p '/usr/lib/postgresql/12/lib/bitcode'/is_jsonb_valid/
/usr/bin/install -c -m 644 is_jsonb_valid.bc '/usr/lib/postgresql/12/lib/bitcode'/is_jsonb_valid/./
cd '/usr/lib/postgresql/12/lib/bitcode' && /usr/lib/llvm-11/bin/llvm-lto -thinlto -thinlto-action=thinlink -o is_jsonb_valid.index.bc is_jsonb_valid/is_jsonb_valid.bc
+ status=0

```

v10:

```
+ sudo make install
/bin/mkdir -p '/usr/share/postgresql/10/extension'
/bin/mkdir -p '/usr/share/postgresql/10/extension'
/bin/mkdir -p '/usr/lib/postgresql/10/lib'
/usr/bin/install -c -m 644 .//is_jsonb_valid.control '/usr/share/postgresql/10/extension/'
/usr/bin/install -c -m 644 .//is_jsonb_valid--0.1.2.sql  '/usr/share/postgresql/10/extension/'
/usr/bin/install -c -m 755  is_jsonb_valid.so '/usr/lib/postgresql/10/lib/'
+ status=0

```

**Comment by theory** [comment]
I think they're different because bitcode support was added in Postgres 12 or (or 11). The `No function matches the given name and argument types. You might need to add explicit type casts.` error sounds like a runtime error. Does it say what function fails? What happens if you try to test from an older commit, like furstenheim/is_jsonb_valid@cc17f6c, which seems to be the last commit where the [tests all pass on all versions](/furstenheim/is_jsonb_valid/actions/runs/3304203256)?

**Comment by furstenheim** [comment]
I've realized my mistake. It was not a cache in docker, but a cache in the Make command. I was running the command, but because the volume is shared, make all was not triggering. Then the binaries were only compatible with postgres 12.

**Comment by theory** [comment]
Oooh, yeah, gotta `make clean` between each version build. :-)
